#!/bin/sh

HOST=""
USERNAME=""
PASSWORD=""
SSHKEY=""
FILEPATH=""
OUTFILE=""
DEVICENAME=""
DEVICEGROUP=""
DEBUG=""

PROGRAM="scp"
OPTS="-oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -q -B"
SSHPASS=`which sshpass`

while read param; do
  if [ -z "$param" ]; then
    continue
  fi
  eqOffset=`expr index "$param" =`
  if [ $eqOffset == 0 ]; then
    echo "Bad parameter: \"$param\""
    exit 1
  fi
  name="${param:0:$[$eqOffset-1]}"
  value="${param:$eqOffset}"
  case "$name" in
  Host)
    HOST="$value"
    ;;
  Username)
    USERNAME="$value"
    ;;
  Password)
    PASSWORD="$value"
    ;;
  SSHKey)
    SSHKEY="$value"
    ;;
  FilePath)
    FILEPATH="$value"
    ;;
  Options)
    OPTS="$value"
    ;;
  Program)
    PROGRAM="$value"
    ;;
  OutFile)
    OUTFILE="$value"
    ;;
  DeviceName)
    DEVICENAME="$value"
    ;;
  DeviceGroup)
    DEVICEGROUP="$value"
    ;;
  Debug)
    DEBUG="$value"
    ;;
  esac
done

if [ -z "$OUTFILE" ]; then
  echo "You must not run this script my itself - only run the parent DBF script"
  exit 1
fi

if [ -z "$HOST" ]; then
  echo "You must specify a Host= line: $DEVICENAME:$DEVICEGROUP"
  exit 1
fi

if [ -z "$USERNAME" ]; then
  echo "You must specify a Username= line: $DEVICENAME:$DEVICEGROUP"
  exit 1
fi

if [ -z "$FILEPATH" ]; then
  echo "You must specify a FilePath= line: $DEVICENAME:$DEVICEGROUP"
  exit 1
fi

if [[ -z "$PASSWORD" ]] && [[ -z "$SSHKEY" ]]; then
  echo "You must specify one of Password= or SSHKey= line: $DEVICENAME:$DEVICEGROUP"
  exit 1
fi

if [[ ! -z "$PASSWORD" ]] && [[ ! -z "$SSHKEY" ]]; then
  echo "You SHOULD specify only one of Password= or SSHKey= line; using SSHKey: $DEVICENAME:$DEVICEGROUP"
fi

if [[ -z "$SSHPASS" ]] && [[ -z "$SSHKEY" ]]; then
  echo "If you want to use password authentication, you must install sshpass: $DEVICENAME:$DEVICEGROUP"
  exit 1
fi

if [ ! -z "$DEBUG" ]; then
  echo "Running with the following parmaters:"
  echo "Host is \"$HOST\""
  echo "Username is \"$USERNAME\""
  echo "FilePath is \"$FILEPATH\""
  if [ ! -z "$SSHKEY" ]; then
    echo "SSHKey is \"$SSHKEY\""
  else
    echo "Password is \"$PASSWORD\""
  fi
  echo "Outfile is \"$OUTFILE\""
fi

if [ ! -z "$SSHKEY" ]; then
  #use SSHKey
  "$PROGRAM" $OPTS -i"$SSHKEY" "$USERNAME"@"$HOST":"$FILEPATH" "$OUTFILE"
  exit $?
else
  #use password
  "$SSHPASS" -p "$PASSWORD" "$PROGRAM" $OPTS "$USERNAME"@"$HOST":"$FILEPATH" "$OUTFILE"
  exit $?
fi
